### ISSUE TITLE
你好，初学者，请教问题。

### ISSUE THREAD

**Issue by xhanglizhu** [licheedev/Android-SerialPort-Tool#2]
Make Project的时候，报错：CreateProcess error=2, 系统找不到指定的文件。
我看了下报错的路径，下面没有bin文件夹。这个如何解决？查资料说，注释：ndk.dir，但还是一样的报错，谢谢。

`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'D:\android\androidSDK\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windows-x86_64\bin\mips64el-linux-android-strip''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:220)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:204)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:340)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
	... 6 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'D:\android\androidSDK\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windows-x86_64\bin\mips64el-linux-android-strip'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
	... 7 more
Caused by: java.io.IOException: Cannot run program "D:\android\androidSDK\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windows-x86_64\bin\mips64el-linux-android-strip" (in directory "D:\android\SerialProtDemo\Android-SerialPort-Tool-master\app"): CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 11 more`

**Comment by licheedev** [comment]
你是将 [Android-SerialPort-API](https://github.com/licheedev/Android-SerialPort-API) 里面的`serialport` module挪到这个[Android-SerialPort-Tool](https://github.com/licheedev/Android-SerialPort-Tool) 里面执行么？
我看错误提示，好像是找不到ndk工具包里面的文件，[Android-SerialPort-Tool](https://github.com/licheedev/Android-SerialPort-Tool) 里面用的jitpack依赖，直接引用的二进制文件，按理是不会再用ndk编译的。
你看看这个有没有下载
![mark](http://p6jf7515z.bkt.clouddn.com/pics/180609/7kaHCAb0fj.png?imageslim)

**Comment by xhanglizhu** [comment]
这个问题换了一台机器就好了。
现在的新的问题是，APP能接收到设备第一条数据，但是设备再发送一条数据，APP就卡死了。
com.licheedev.serialtool E/SerialReadThread: run(SerialReadThread.java:30)开始读线程
到这个位置就卡死了。
PC端模拟串口(友善串口调试助手发的数据)

现在貌似又可以了，我看看怎么修改成ASASCII 文本模式。
非常感谢。

**Comment by licheedev** [comment]
@xhanglizhu 你的app的安装环境是什么？这串口的api，兼容性其实一般。
我偶尔用‘genymotion’+`vbox`+`Configure Virtual Serial Port Driver`去模拟串口调试，
![mark](http://p6jf7515z.bkt.clouddn.com/pics/180609/6EGiFA0K4h.png)

如果用7.0的模拟器镜像，一打开串口就卡死了，6.0的镜像就无问题。
还试过部分开发板，运行这个串口api后一段时间，无收发任何数据，开发板就直接重启的情况。

这个DEMO，读写都是在子线程运行的，不过打开串口那一步没在子线程里面运行，是个隐患。
如果出现卡死的情况，很可能就是兼容性问题了。

**Comment by xhanglizhu** [comment]
@licheedev APP运行环境是官方的模拟器，使用emulator @n5 -qemu -serial COM2 开启。
`Name: n5
CPU/ABI: Intel Atom (x86)
Path: C:\Users\name\.android\avd\Nexus5.avd
Target: default [Default] (API level 19)
Skin: 2560x1600
SD Card: 100 MB
hw.dPad: no
hw.lcd.height: 1600
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 10
vm.heapSize: 192
skin.dynamic: yes
hw.device.manufacturer: Google
hw.lcd.width: 2560
hw.gps: yes
hw.initialOrientation: landscape
skin.path.backup: _no_skin
image.androidVersion.api: 19
hw.audioInput: yes
image.sysdir.1: system-images\android-19\default\x86\
tag.id: default
showDeviceFrame: no
hw.camera.back: emulated
hw.mainKeys: no
AvdId: n5
hw.camera.front: emulated
hw.lcd.density: 320
avd.ini.displayname: n5
hw.arc: false
hw.gpu.mode: auto
hw.device.hash2: MD5:8323741337b2d5dd4418b47c06a242b0
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.battery: yes
hw.cpu.ncore: 2
hw.sdCard: no
tag.display: Default
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: no
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes`

如果使用Hex模式，收发没有什么问题。代码更改：
1.发送字符串模式，可以录入0-9&A-Z等字符串。
SerialPortManager.sendCommand中修改：
`byte[] bytes =command.getBytes();// ByteUtil.hexStr2bytes(command); `
2.接收字符串模式，接收字符串，代码更改：
SerialReadThread.onDataReceive中修改：
`//String hexStr = ByteUtil.bytes2HexStr(received, 0, size);
        //LogManager.instance().post(new RecvMessage(hexStr));
        String Str = null;
        try {
            Str = new String(received,0,size,"US-ASCII");
            LogManager.instance().post(new RecvMessage(Str));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
            System.out.println(e);
        }`

APP有时候可以接收到第一条消息，第二条就不行卡死了，
有时候，APP发送几条，一接收就卡死了。

**Comment by heroxu** [comment]
编译能通过，运行到真机或者模拟器时，报Cause: error=2, No such file or directory

**Comment by jaredtech** [comment]
Cause: error=2, No such file or directory 的看看是不是下了ndk，如果是再看看用的是不是ndkr16的版本。我的r16没问题

**Comment by licheedev** [comment]
@jaredtech 是已经编译并安装成功了？Google提供的这个串口API需要对串口设备映射的文件有读写权限，普通手机和官方的模拟器，是没root权限的，是无解的。
可以用genymotion和虚拟串口驱动做模拟调试。
https://github.com/licheedev/Android-SerialPort-Tool/issues/2#issuecomment-395934160
